[[headers]]
  for = "/*"
  [headers.values]
    Netlify-CDN-Cache-Control = "public, maxage=86400, stale-while-revalidate=31536000",
    CDN-Cache-Control = "public, maxage=86400, stale-while-revalidate=31536000"
    X-Foo = "bar"